server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shopdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin

  messages:
    basename: errors # Register error code file [default : messages]

  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql : true #To beautify or pretty print the SQL
        default_batch_fetch_size: 1000

    show-sql: true  # show sql

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한

logging:
  level:
    org.hibernate.type: debug #show parameter binding
    SQL: debug

file:
  upload:
    path: D:/


kakao:
  client:
    id: 6594f294f8e57fa6081622acfac6dffd # todo 자기 자신의 kakao.client.id 입력
    secret: lKUgsZZje5WzBzblvXonh7M9gYgj3NiD

token:
  secret: jwt-token-secret # todo 자신의 jwt token secret키 입력
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주